language: php
notifications:
  email: false
php:
    - 7.2
    - 7.3
    - 7.4
script:
    - ./vendor/bin/phpunit
    - ./vendor/bin/phpcs --standard=PSR2 src
before_script:
    - composer self-update
    - composer install --dev --no-interaction --prefer-source
